### ISSUE TITLE
[backend] - customize Swagger UI with title and entities tags

### ISSUE THREAD

**Issue by jkrobicki** [dyvenia/timesheets#25]
Description: optimizing timesheets app swagger UI with tags, title and description for clearer view

#### Current state: 
![image](https://user-images.githubusercontent.com/88193723/149545860-71fe508f-69a3-468c-b4c7-3dae77320922.png)
#### Future state:
- endpoints grouped by entity
- title  "timesheets app API" added
#### Tasks:
- [ ] add title parameter "timesheets app API" in object `app = FastAPI()`
- [ ]  create metadata for entities tags
- [ ] add metadata for each entity to `openapi_tags` parameter
#### PR link: https://github.com/dyvenia/timesheets/pull/43

**Comment by jkrobicki** [comment]
### Acceptance criteria
In OpenAPI Specification endpoints are sorted in blocks for easier orientation

![image](https://user-images.githubusercontent.com/88193723/147585002-94949c26-5842-441c-93e7-a90290a1f73c.png)
### Tasks
- use tags in path parameters

**Comment by jkrobicki** [comment]
@acivitillo
