### ISSUE TITLE
[backend] - create tests for client API

### ISSUE THREAD

**Issue by jkrobicki** [dyvenia/timesheets#34]
Description: testing all Client API endpoints with pytest.

### Tasks

- [x] create a test for the post endpoint "/" https://github.com/dyvenia/timesheets/pull/35
- [x] create a test for the get endpoint "/" https://github.com/dyvenia/timesheets/pull/36
- [x] create a test for the get endpoint "/{client_id}" https://github.com/dyvenia/timesheets/pull/37
- [x] #38 https://github.com/dyvenia/timesheets/pull/40
- [x] create a test for the put endpoint "/{client_id}/new-name" https://github.com/dyvenia/timesheets/pull/41
- [x] create a test for the delete endpoint "/{client_id}" https://github.com/dyvenia/timesheets/pull/42
### Acceptance Criteria

All Client API endpoints are tested with the pytest tool and the module is in /tests/test_api_client.py

**Comment by jkrobicki** [comment]
@acivitillo can you please review and accept this issue?

**Comment by acivitillo** [comment]
can you review the put endpoints? I am not sure you should use URL parameters for those, maybe you need to use {client_id} endpoint

**Comment by jkrobicki** [comment]
Ok, I'll look into it

**Comment by jkrobicki** [comment]
@acivitillo you're right, put endpoint should be "/{client_id}"

**Comment by acivitillo** [comment]
I believe the end point for put should be `/{client_id}/new_name`

**Comment by jkrobicki** [comment]
@acivitillo shouldn't it be with the hyphen then? `/{client_id}/new-name`

**Comment by acivitillo** [comment]
yes it can be
