### ISSUE TITLE
create a test for the get endpoint "/{client_id}/epics/"

### ISSUE THREAD

**Issue by jkrobicki** [dyvenia/timesheets#38]
Describtion: create a test for the get endpoint "/{client_id}/epics/"

#### Tasks:
- [ ] in backend/tests/test_client_api.py create test_read_clients_epics function
- [ ] #39
- [ ] define response for get method "api/clients/1/epics" endpoint 
- [ ] assert response data == ` {"id": 1, "name": "dyvenia", "name_1": "[dyvenia]branding"}
 `

**Comment by jkrobicki** [comment]
@acivitillo please take a look. This issue is tracked in a main one. Do you understand my problem? Or its to complex and better if I just write it with words?

**Comment by jkrobicki** [comment]
Problem description:
- I want to test get method "/{client_id}/epics/"
- it uses joins - select(Client.name, Epic.name)
- as I run `pytest` command error "not found" appears
- as I understand correctly, as I use test db `db_name = "test_db.sqlite"` I need to implement epic table with data first, to be able to join on it
- as fixture "client"  runs with scope="module" it tears down in a test_epic_api.py with delete "api/epics/" method
 
My solution:
- I move fixtures "client", "session" and "create_db" into new file conftest.py
  -   now fixtures are available for the whole subpackage and don't need to be imported
- I change `scope="session"` in "create_db" fixture 
  -  now the fixture runs between modules
- with `pytest-order` I order post methods to run first and delete methods to run last

@acivitillo

**Comment by acivitillo** [comment]
yes that's correct, I am not sure you need `pytest-order` but use that for now and then let's review later. Yes you need to do things in the right order with these tests.
