### ISSUE TITLE
create tests for timelog API

### ISSUE THREAD

**Issue by jkrobicki** [dyvenia/timesheets#49]
Description: testing all Timelog API endpoints with pytest.
### Tasks

- [ ] create a test for the post endpoint "/" https://github.com/dyvenia/timesheets/pull/50
- [ ] create a test for the get endpoint "/" https://github.com/dyvenia/timesheets/pull/50
- [ ] create a test for the get endpoint "/users/{user_id}/months/{month}/years/{year}/clients/{client_id}" https://github.com/dyvenia/timesheets/pull/50
- [ ] create a test for the put endpoint "/{timelog_id}/new-start-time" https://github.com/dyvenia/timesheets/pull/50
- [ ] create a test for the delete endpoint "/{timelog_id}" https://github.com/dyvenia/timesheets/pull/50

### Acceptance Criteria

All Timelog API endpoints are tested with the pytest tool and the module is in /tests/test_api_timelog.py
