### ISSUE TITLE
[backend] Create calendar entity with auto-implemented data

### ISSUE THREAD

**Issue by jkrobicki** [dyvenia/timesheets#51]
Description: New table "calendar" with one row for each date

### Acceptance criteria:
- added entity `calendar`
- entity `calendar` consists of fields: date, year, month_number, month_name, mmy-yy, day_number,  day_name, fiscal_q
- entity `calendar` is implemented on application spin up
### Tasks:
- [ ] create model `Calendar` with attributes:
```python
date: datetime 
year_number: int
year_name: str
quarter_number: int
quarter_name: str
month_number: int
month_name: str
week_number: int
week_name: str
week_day_number: int
week_day_name: str
```
- [ ] add excel file "CalendarTable.xlsx" to timesheets/backend/ 
- [ ] add code to in main.py:
- read excel file
- implement `Calendar` model with data from "CalendarTable.xlsx"
- [ ] run it on start_up

**Comment by jkrobicki** [comment]
@acivitillo
